#此文件存放路径为/opt/1panel/conf/app.yaml
system:
  db_file: 1Panel.db
  base_dir: /opt
  mode: dev
  repo_url: https://resource.fit2cloud.com/1panel/package
  app_repo: https://apps-assets.fit2cloud.com
  is_demo: false
  port: 9999
  username: admin #初始用户名
  password: admin123 #初始密码
log:
  level: debug
  time_zone: Asia/Shanghai
  log_name: 1Panel
  log_suffix: .log
  max_backup: 10
dir:
  app: /jetsonDetect/
  app_config: /jetsonDetect/config/config.json
  result: /jetsonDetect/res/
  app_log: /jetsonDetect/log/
  test_video: /jetsonDetect/video/