system:
  db_file: 1Panel.db
  base_dir: /opt
  mode: dev
  repo_url: https://resource.fit2cloud.com/1panel/package
  app_repo: https://apps-assets.fit2cloud.com
  is_demo: false
  port: 9999
  username: admin
  password: admin123

log:
  level: debug
  time_zone: Asia/Shanghai
  log_name: 1Panel
  log_suffix: .log
  max_backup: 10

dir:
  app: /jsonDetect/
  app_config: /jetsonDetect/config/config.json
  result: /jsonDetect/res/
  app_log: /jsonDetect/log/

